### PR TITLE
Subtly redesign the Trash icon

### PR DESCRIPTION
**Pull request by jasmussen**
In this PR I'd like to propose some small tweaks to the trash icon. There are two purposes to this:

1. Allow it to scale better
2. Reduce the overall silhuette

Both of these come as a result of using the trash icon next to blocks in the Gutenberg editor project. For every block you click, you'll see a trash can you can click to remove that block.

screen shot 2017-06-23 at 10 09 18

Screenshots. Before:

screen shot 2017-06-23 at 10 06 25

After:

screen shot 2017-06-23 at 10 06 19

Vectors:

screen shot 2017-06-23 at 10 06 34

In context:

screen shot 2017-06-23 at 10 07 44

By reducing the complexity of the shape, we make that visual load lighter.

An additional trick, is scaling the icon to 75%. Scaling outside of the pixel grid is usually a no-no, but there are increments where pixels look their best when scaled. This usually means 2x and 3x, but .75x and .5x can work too. For Gridicons, we are pondering embracing .75x too. That set is at a 24px base grid, so .75x would give us 18px. Many icons, especially solids, scale well to this size without further work, and we are looking into a way to load individually hinted versions for that size, for the icons that need it.

For Dashicons this means we can possibly make some scaling exceptions, and show a few icons, usually solids, at 15px, and it'll still look pretty good. This would further reduce the visual load of having the trash button near every block in Gutenberg.

Scaled to .75x:

screen shot 2017-06-23 at 10 07 58

### CODE REVIEW

**Comment by field2** [comment]
I like the texture of the vertical lines in the current one, but I agree the extra details decrease the impact of the density/silhouette of the icon, especially at 75%. While it won't break anything out there, some people might get a shock seeing a different trash icon in their dashboards/plugins/widgets, etc. Would it make more sense to do this as an alt version and keep the current one?
Also, is scaling to 75% something we'll be considering for other dashicons?

**Comment by jasmussen** [comment]
> Would it make more sense to do this as an alt version and keep the current one?

So long as it looks like a trash can, I would not worry. I understand the concern, but we also need to be able to modernize if we truly think the new thing is better.

> Also, is scaling to 75% something we'll be considering for other dashicons?

I think very long term it could be interesting to look at a more standard 18 and 24px grid for dashicons. These are sizes that also scale well to mobile icon standards. But in the mean time, yes, I think it could make sense to also scale a few others, like the cog (which already translates well) to 75%.

**Comment by field2** [comment]
OK, this is good to merge.

**Comment by jasmussen** [comment]
Rebased, grunted, merging.

**Pull request merged**
