### PR TITLE
Fix issues discovered in recent core merge

### PR DESCRIPTION
**Pull request by jasmussen**
*Do not merge this until reviewed*.

This PR addresses issues found in https://github.com/WordPress/dashicons/pull/349#issuecomment-476145307:

- Some broken vector shapes
- Some incorrect mappings
- Some missing icons

Please refer to the comment above to see the full list of edits.

Please, check this commit out, test it, test the build process, verify the individual SVGs that changed, and please test the various mappings.

CC: @desrosj

### CODE REVIEW

**Comment by jasmussen** [comment]
From the comment, here's the list of issues discovered and their status in this PR:

**Icons that are new (and therefore codepoint doesn't matter):**

- admin-site-alt
- admin-site-alt2
- admin-site-alt3
- businessperson
- businesswoman
- color-picker
- editor-ol-rtl — the vectors in this one are broken
- instagram
- rest-api — the vectors in this one are broken
- tide
- yes-alt


**Icons that are missing or weird:**

- [x] a duplicate arrow-ip at F143
- [x]  unused-camera-alt is in svg-unused but should be at F129
- [x] "cloud" is mapped to F176 in old, appears as 2601 in new font
- [x] "minus" is f460 in old, is 2212 in new
- [ ] there's a new "plus" icon in 002B in the new font, that doesn't appear needed or used in the old font
- [x] "calendar" is f145 in the old font, is 1F4C5 in the new
- [x] "camera" is F306 in the old, 1F4F7 in the new
- [x] "clipboard" is F481 in the old, but 1F4CB in the new
- [x] "hammer" is F308 in the old, but 1F528 in the new
- [x] there's some issues with "lock" — there's a "lock-alt" in svg-unused that gets included at address 1F512 in the new font, and there's a very similar but more rounded looking lock icon at F315 in the old font. We should figure out WHICH lock icon is the right one, delete the unused ones, and map the result to F315 in the new font.
- [x] F302 contains a very obsolete version of the Twitter logo. This is stored in svg-unused, and is not part of the new font. 
- [x] microphone is at F482 in the old font, and at 1F3A4 in the new font.
- [x] there's a little chunky menu icon at F329 that does not appear to be part of the new font. It's "unused-menu"
- [x] "paperclip" is at F546 in the old font, and 1F4CE in the new
- [x] "plugins-checked" from unused folder is at F485 in the old font, does not appear in the new
- [x] "text-page" is at F121 in the old, does not appear in the new
- [x] "update" exists in two versions. the one from the unused folder maps to F113 in the old font, doesn't appear in the new. But "update", which is mirrored appears at F463 in both fonts

NOTE that some of the above icons are currently stored in svg-unused, but since they ARE actually used they should be moved out of that folder

**Codepoints that need fixing:**

- [x] buddicons-bbpress-logo, should be F477, is F12B
- [x] editor-ltr, should be at F320, is at F129
- [x] editor-rtl needs a sanity check, it points leftward in new font, rightwards in old font
- [x] email-alt2 is F10A, should be F467

**Comment by jasmussen** [comment]
A few good tools:

https://www.branah.com/unicode-converter — allows you to convert from Decimal to UTF-16 (which roughly translates to what is used in CSS to pick a particular character).

I would recommend a different font app than Glyphs Mini, mostly because I used that and it reported some issues around specific character mappings around the cloud and camera. These were correct in the font, but incorrectly identified in Glyphs. Perhaps FontForge might work better?

**Comment by desrosj** [comment]
These are looking good, @jasmussen!

I went through character by character and ensured the new font in this branch matched the old font. I found a few more issues:

- The old font has a lock icon stored at f160. This is missing in the new font files in this branch.
- The icons at f171/f172 in the old font are different than the icons at those locations in the new font.
- The icon at f182 is different. Maybe we should introduce the new icon as a "trash-alt".
- It looks like the "editor-rtl" and "editor-ltr" are reversed. The LTR is in the current font as f320, but it's in the new font as f10c, and the original position is replaced with the new RTL version.
- The f327 icon is missing in the new font. It appears to be a slightly larger version of "edit" at f464 (which is present for both versions).
- f349 is missing in the new font. I _think_ this is the `unused-menu-alt-2.svg` file in the unused folder.
- f494 is missing in the new font. This appears to be the same icon as "editor-code" icon stored at f475.

After we fix these, let's double check the class names match up to the same characters and we should be good to go!

**Comment by jasmussen** [comment]
Awesome, thanks for the review. I'll address your points first thing tomorrow and we'll get the show on the road.

**Comment by jasmussen** [comment]
> The icons at f171/f172 in the old font are different than the icons at those locations in the new font.

This is an intentional redesign, same with ...

> The icon at f182 is different. Maybe we should introduce the new icon as a "trash-alt".

Your thought that we could introduce the redesigns as an "alt" is something worth considering, but (and even though we're in a beta crunch) I'd love to discuss/PR this separately. The designs are featured heavily in the new block editor, and it seems like it'd be worth having consistency across where those icons are used. They also mean the same, so it's not necessarily going to be a point of confusion.

Addressed your remaining points (and I took the liberty to edit your comment to add checkboxes, because I like checkboxes). 

Lotta menus now:

Screenshot 2019-03-26 at 09 35 00

I think we should be good to get this big whopper in. There are unfortunately a bunch of duplicates now, but this appears to always have been the case — now it's just more visible because things are alphabetical.

Note that I'm seeing _some_ weirdness when opening this file in Glyphs, as I also alluded to yesterday. So I think we should look at the unicode values that are output in the CSS file, and actually test using the browser, as opposed to look in Glyphs.

**Comment by desrosj** [comment]
Looks good except f475 is still missing.

My primary concern with the icons changing is backwards compatibility. I'll open a new issue so we can discuss.

I am working on reviewing the CSS definitions now for parity.

**Comment by desrosj** [comment]
Lastly, it appears the `.dashicons-editor-code-duplicate` definition is not needed. The character exists in the font, but it does not currently have a CSS definition.

**Comment by desrosj** [comment]
My latest changes address all the feedback items I mentioned, except the trash and undo redo differences.

**Comment by jasmussen** [comment]
Thank you for the changes @desrosj. I took them for a spin, and looked at the code. All your changes look good, and the rendered font in the example file look good too:

Screenshot 2019-03-27 at 11 52 11

☝that's zoomed out to fit all the icons, don't worry they aren't squished.

I think this is good to go!

**Comment by desrosj** [comment]
I opened #352 to discuss my last piece of feedback. Thanks for the review, @jasmussen!

**Pull request merged**
