### PR TITLE
Add cloud saved and cloud upload icons

### PR DESCRIPTION
**Pull request by jasmussen**
We're looking at adding an icon for the "Save Draft" button in Gutenberg. As part of that, we need an icon for "Save to cloud" and "Saved", and we'd very much like to avoid the floppy disk.

This PR adds two cloud-based icons for that.

Save to cloud, or `cloud-upload`:

screen shot 2018-02-28 at 10 55 41

screen shot 2018-02-28 at 10 55 46

Saved in cloud, or `cloud-saved`:

screen shot 2018-02-28 at 10 57 09

screen shot 2018-02-28 at 10 57 13

### CODE REVIEW

**Comment by jasmussen** [comment]
Moved the clouds upwards 1px to better align with text:

screen shot 2018-02-28 at 11 12 08

This includes the existing `cloud` dashicon.

**Comment by field2** [comment]
Looks great.

**Comment by jasmussen** [comment]
Per discussion in #269, I'm going to rebase and merge this with the "Looks great." as approval :)

**Comment by swissspidy** [comment]
Just want to point out that an upload icon to indicate saving a post feels pretty weird…

**Pull request merged**
