### PR TITLE
Renaming exerpt-view.svg to excerpt-view.svg

### PR DESCRIPTION
**Pull request by iamgabrielma**
Fixes typo on svg/excerpt-view.svg file . Related to https://github.com/WordPress/gutenberg/pull/1238

### CODE REVIEW

**Comment by jasmussen** [comment]
Thanks for the pr! 

Because we are also building a font file from this now, there's a Unicode code points file which we need to update, to ensure the icon shows up the right place in the font. I can take a look at this Monday.

**Comment by jasmussen** [comment]
Yep, here's the code to fix, should be easy:

https://github.com/WordPress/dashicons/blob/master/codepoints.json#L107

If you can update that file to be spelled correctly, then try and run `npm run build` and verify that the font looks cool, then I think this PR would be good to merge! Thanks so much.

**Comment by iamgabrielma** [comment]
Thanks for the guidance @jasmussen , found and fixed the same typo in dashicons.css and dashicons.html and seems that works fine.

**Comment by jasmussen** [comment]
Nice work!

I think the dashicons.css and html files are automatically created. Did you try running `npm run build`? (Need Node installed, and to run `npm install` first).

**Comment by iamgabrielma** [comment]
>  Did you try running npm run build? (Need Node installed, and to run npm install first).

Yep! I got an error following the Mac installation though, `--with-python does not exist` so it skipped it. 

On the other hand, all tasks ran and passed `OK` and `done without errors`,  however,  I'm seeing duplication (?), not sure if this is normal or how to test it further after `npm install`

Examples:
[img](https://cloudup.com/c_0Dy00LG1M)
[img](https://cloudup.com/coe_hwTKJYL)
[img](https://cloudup.com/cH5_sXa8bN2)

**Comment by field2** [comment]
Good to merge, @jasmussen please handle this.

**Comment by jasmussen** [comment]
Thanks so much for your contribution @iamgabrielma!

I couldn't rebase this branch, so I created a new one in #209, and gave you credit. Will note you down for Gutenberg credit also.

**Pull request closed without merging**
