### PR TITLE
Correct invalid CSS property

### LINKED ISSUE #422: CSS validation issue
Hello, I have ran an HTML validator on my website,
It has gathered several errors tied to dashicon:

> Error: CSS: speak: none is not a speak value.

```
.dashicons{
	font-family:dashicons;
	display:inline-block;
	line-height:1;
	font-weight:400;
	font-style:normal;
	**speak:none;**
	text-decoration:inherit;
	text-transform:none;
	text-rendering:auto;
	-webkit-font-smoothing:antialiased;
	-moz-osx-font-smoothing:grayscale;
	width:20px;
	height:20px;
	font-size:20px;
	vertical-align:top;
	text-align:center
	}
```
is there a way to remove the error?

Thanks

### PR DESCRIPTION
**Pull request by desrosj**
`none` is not a valid value for the `speak` CSS property. `never` is the correct value.

Fixes #422.

### CODE REVIEW

**Comment by field2** [comment]
Considering that dashicons is at end of life, does it make sense to pursue this issue?

**Review by jasmussen — APPROVED** [review]
Nice change, thank you. I verified the CSS looks good, and even though multiple files are updated, it's cache query strings. Ship it!

**Comment by jasmussen** [comment]
@field2 Although Dashicons is wrapping, the most recent version of the font is the best version, and is still part of WordPress, and likely will be forever. So I think this fix will be appreciated!

**Comment by desrosj** [comment]
Thanks everyone! Though Dashicons is retired, I think we should still fix bugs (within reason) and make changes to maintain compatibility with new versions of WordPress.

**Pull request merged**
