### PR TITLE
Add icon for Unlink and Shortcode

### LINKED ISSUE #261: Need shortcode dashicon for Gutenberg
In Gutenberg v2.0.0 the shortcode block currently has a label of Shortcode prefixed by the dashicons-editor-code, which looks like this `<>`. It would be much better if it looked like a shortcode `[]`. 
The same shortcode dashicon should also be used in the add block dialog. Currently it uses dashicons-marker, a big `O`.

### PR DESCRIPTION
**Pull request by jasmussen**
Unlink is the reverse of link. What it does on click is to _break a link_, unlink it, stop it from being a link. Requested by @karmatosed for an iteration on the link interface.

screen shot 2018-02-09 at 11 27 03

screen shot 2018-02-09 at 11 27 09

The other icon is for shortcodes. Fixes #261. It's for the shortcode block.

screen shot 2018-02-09 at 11 33 28

screen shot 2018-02-09 at 11 33 24

### CODE REVIEW

**Comment by field2** [comment]
Can we "flatten" the top and bottom edges of the slash in the shortcodes icon?

**Comment by field2** [comment]
Also, does this unlink meant to replace what we alreqdy have? See https://developer.wordpress.org/resource/dashicons/#editor-unlink

**Comment by jasmussen** [comment]
Yes, I'll flatten the top and bottom edges of the slash, and oh my — I didn't realize that there was already an unlink icon — looks like Tammie missed that too. I believe the request was on the Gutenberg Github. I'm afk next week, but maybe I'll tweak this PR today real quick to address your feedback and to remove the unlink icon.

**Comment by jasmussen** [comment]
screen shot 2018-02-11 at 07 05 31

How's that?

Also, removed the unlink icon.

**Comment by field2** [comment]
Looks good, but will this conflict with the PR I just did?

**Comment by jasmussen** [comment]
Yes but if you give me a thumbs up I will rebase, fix, and merge 🙂

**Comment by jasmussen** [comment]
Per discussion in https://wordpress.slack.com/archives/C03EESJAW/p1519836029000445 and based on your "looks good", I'm goign to merge this, rebase #274, and merge that after.

**Pull request merged**
