### PR TITLE
Add new icons for embeds, and default block

### LINKED ISSUE #203: Embed Icons: New icons for different types of embeds
In the Gutenberg editor, we are creating embed aliases for every oembed WordPress supports. There are a lot of them:

screen shot 2017-06-21 at 10 13 47

Don't worry, these embeds will get a separate tab in the inserter (see https://github.com/WordPress/gutenberg/issues/1325) —  they are mostly there so that you can search. This helps fix the "mystery meat embed discovery" issue. Did you know you can embed a WordPress post into a WordPress post? I sure didn't. I know now. Yo dawg.

However this is a lot of logos, and as we add oembeds in the future, even more will come. Keeping and maintaining logos in an icon set like this is a losing game, which is why for [Gridicons](https://automattic.github.io/gridicons/) we have a strict no logos rule (and put all logos into [a separate set instead](https://github.com/Automattic/social-logos)).

How about we create multiple embed icons. One that is an absolutely generic embed, and then multiple specific embeds, like "video embed", "post embed", things like that? Here's a quick brainstorm:

- Every icon should probably have the same _silhuette_. Like a horizontal square, which is the usual shape of an embed.
- The generic embed could be this silhuette, with a tiny code bracket and some sort of media icon
- Video embed could be the silhuette with a play button (kind of like the current generic embed)
- Audio embed: same as above but with musical note
- Photo embed: same as above but with photo
- Gallery embed: same as above but with gallery
- Post embed: same as above, but with pin/post icon
- "Widget" embed (like polldaddy, slideshare, other embeds that adds features to your site): silhuette but perhaps with a cog inside?

CC: @TheTracyL @field2 @folletto

### PR DESCRIPTION
**Pull request by jasmussen**
This fixes #203

This PR adds a generic "block" icon, necessary for Gutenberg

In addition to this, it adds a generic "embed" block, as well as a few other topical embed blocks:

- post embed
- audio embed
- photo embed
- video embed

Note, these icons are placed in the "Gutenberg" directory, which means it does not get added to the icon font.

Screenshots:

screen shot 2017-10-13 at 10 58 09
screen shot 2017-10-13 at 11 26 36
screen shot 2017-10-13 at 11 26 42
screen shot 2017-10-13 at 11 26 46
screen shot 2017-10-13 at 11 26 51
screen shot 2017-10-13 at 11 27 03

screen shot 2017-10-13 at 11 30 37

### CODE REVIEW

**Comment by folletto** [comment]
What I feel works well:

1. The shape and structure
2. The way it locks together type icon and embed icon

What I find not ideal:

1. Video having a different structure and locking
2. Embed generic using the "code" icon, and being different

My advice would be to have the same identical baseline, and reuse it.

This is a crappy mock of what I mean (especially crappy for video):

screen shot 2017-10-13 at 12 36 34

**Comment by field2** [comment]
I see what @folletto is saying, and I think it's right. They're a good representation of blocks of code, but should be more consistent–the brackets should be the same size and place, and the "sub-icon" should be reversed out like in audio and post. Having no "sub-icon" in generic is fine. Photo should be enclosed; the subicon shouldn't share a border with the main icon. The video subicon should be enclosed and white.

**Comment by jasmussen** [comment]
Solid, solid feedback. Will address it monday! Thanks all!

**Comment by field2** [comment]
screen shot 2017-10-13 at 10 17 47 am
screen shot 2017-10-13 at 10 17 28 am
Sorry for the cruddy screenshots, but here's a suggestion for unifying the look of these. They're 18px wide now, so it's hard to say if they'd look weird with the other gutenberg embed icons.

**Comment by jasmussen** [comment]
I dig every one of those, Ben, except the generic one. It feels like the generic one would actually work better without the asterisk — I understand why you did this, but after seeing Davide's empty one I was like, yeah, that works.

**Comment by jaymanpandya** [comment]
+1 on @jasmussen for the generic icon. 😊 they look awesome. 😍

**Comment by field2** [comment]
I actually did a generic one without asterisk, but forgot to post. Yep, it's better without it.

**Comment by jasmussen** [comment]
Solid! Ben, feel free to add your updated SVG files to this branch, overwrite mine. Okay to push. I can grunt/build and rebase if need be. Thanks for the help.

**Comment by jasmussen** [comment]
This branch got a little messy, so I created a new one and merged your icons with the permission given in Slack.

**Pull request closed without merging**
