### PR TITLE
alternative admin-site icons

### PR DESCRIPTION
**Pull request by field2**
for https://github.com/WordPress/dashicons/issues/95

### CODE REVIEW

**Comment by field2** [comment]
This pr addresses https://github.com/WordPress/dashicons/issues/95 and https://core.trac.wordpress.org/ticket/41074 . I added an additional site icon, just a generic circle with lines. It may be bet to ditch all the representational globe icons and just use this one, instead of adding 3 new icons.

**Comment by jasmussen** [comment]
Built the files for you —  they built fine, and pushed. So important that you `git pull` before making any new changes. 

Globes look cool to me. Oceania is a bit small, but hey, works:

screen shot 2017-06-23 at 13 01 33

**Comment by field2** [comment]
I did git pull before I made these, but in the meantime there've been several new PRs. Could you either handle the PR or let me know how to resolve any conflicts if I do it? Also, if the Oceania icon could use tweaking, please have a run at it; at this point my eyes are sore from pushing vectors :)

**Comment by jasmussen** [comment]
No no, I mean I made a commit here: https://github.com/WordPress/dashicons/pull/204/commits/4509456d3c7518c754a51b8051d7a90bfe8db014 —  right above. Which means if you pull again you get the built files.

**Comment by field2** [comment]
Let's merge this.

**Comment by jasmussen** [comment]
Rebased, grunted, merging.

**Pull request merged**
